import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '../styles/Home.module.css'
import Header from '../components/Header';
import Bannner from '../components/Bannner';
import SmallCard from '../components/SmallCard';
import MediumCard from '../components/MediumCard';
import LargeCard from '../components/LargeCard';
import Footer from '../components/Footer';


const inter = Inter({ subsets: ['latin'] })

export default function Home({ exploreData, cardsData }) {
  return (
    <div >
      <Head >
        <title>airbnb</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <Bannner />

      <main className='mx-6 xl:max-w-6xl xl:mx-auto my-5 '>
        <section1 className='p-3'>
          <h1 className='text-xl m-2 font-semibold 2xl:text-3xl  xl:text-3xl  md:text-2xl sm:text-xl  '>Explore Nearby</h1>
          <div className='grid grid-cols-1 xl:grid-cols-4 lg:grid-cols-3 md:grid-cols-2'>
            {exploreData?.map(item => (
              <SmallCard img={item.img} location={item.location} dist={item.distance} />
            ))}
          </div>
          {/* {console.log(exploreData)} */}
        </section1>
        <section2>
          <h1 className='text-xl m-2 font-semibold 2xl:text-3xl  xl:text-3xl  md:text-2xl sm:text-xl  '>Live Anywhere</h1>
          <div className='flex overflow-scroll scrollbar-hide'>
            {cardsData.map((item) => (
              <MediumCard img={item.img} title={item.title} />
            ))}
          </div>
        </section2>

        <LargeCard
          img="https://a0.muscache.com/im/pictures/2da67c1c-0c61-4629-8798-1d4de1ac9291.jpg?im_w=1440" title="The Greatest Outdoors" description="Wishlists curated by Airbnb." buttonText="Get Inspired"
        />

        <Footer />
      </main>
    </div>
  )
}

export async function getStaticProps() {
  const exploreData = await fetch('https://www.jsonkeeper.com/b/4G1G').then((res) => res.json());
  const cardsData = await fetch('https://www.jsonkeeper.com/b/VHHT').then((res) => res.json());

  return {
    props: {
      exploreData: exploreData,
      cardsData: cardsData
    }
  }
}

